# Translations template for PROJECT.
# Copyright (C) 2024 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2024.
#
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2024-06-25 17:01+0200\n"
"PO-Revision-Date: 2025-07-07 06:24+0000\n"
"Last-Translator: PanierAvide <adrien@pavie.info>\n"
"Language-Team: French <http://weblate.panoramax.xyz/projects/panoramax/api/"
"fr/>\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n > 1;\n"
"X-Generator: Weblate 5.4.3\n"
"Generated-By: Babel 2.15.0\n"

#: geovisio/templates/main.html:45
msgid "Simple 360° geolocated pictures hosting"
msgstr "Hébergement facile de photos géolocalisées"

#: geovisio/templates/main.html:47
msgid "Full page version"
msgstr "Version pleine page"

#: geovisio/templates/main.html:51
msgid "Viewer"
msgstr "Visionneuse"

#: geovisio/templates/main.html:52
msgid "Embed pre-configured viewer"
msgstr "Embarquer la visionneuse pré-configurée"

#: geovisio/templates/main.html:53
msgid "Easiest way to have a working GeoVisio viewer on your website"
msgstr ""
"La méthode la plus simple pour embarquer la visionneuse GeoVisio sur votre "
"site web"

#: geovisio/templates/main.html:59
msgid "Use JS library"
msgstr "Utiliser la bibliothèque JS"

#: geovisio/templates/main.html:60
msgid "A completely configurable viewer for your website"
msgstr "Une visionneuse entièrement configurable pour votre site web"

#: geovisio/templates/main.html:82
msgid "Links"
msgstr "Liens"

#: geovisio/templates/main.html:84
msgid "Pictures viewer"
msgstr "Visionneuse photos"

#: geovisio/templates/main.html:86
msgid "API docs"
msgstr "Doc de l'API"

#: geovisio/templates/main.html:88
msgid "JS library docs"
msgstr "Doc de la bibliothèque JS"

#: geovisio/templates/main.html:90
msgid "Repositories"
msgstr "Dépôts logiciels"

#: geovisio/templates/viewer.html:22
msgid "You need to enable JavaScript to run this app."
msgstr "Vous devez activer JavaScript pour exécuter cette application."

#: geovisio/utils/auth.py:164
msgid "Authentication is mandatory"
msgstr "L'authentification est obligatoire"

#: geovisio/utils/auth.py:292
msgid "Only Bearer token are supported"
msgstr "Seul le « Bearer Token » est supporté"

#: geovisio/utils/pictures.py:302
#, python-format
msgid ""
"Invalid '%(format)s' format for image, only the following formats are "
"available: %(allowed_formats)s"
msgstr ""
"Format d'image \"%(format)s\" invalide, seuls les formats suivants sont "
"autorisés : %(allowed_formats)s"

#: geovisio/utils/pictures.py:418
msgid "Picture can't be found, you may check its ID"
msgstr "Photo introuvable, vérifiez son identifiant"

#: geovisio/utils/pictures.py:421
msgid "Picture is not available (either hidden by admin or processing)"
msgstr "Photo non-disponible (soit cachée, soit en cours de traitement)"

#: geovisio/utils/pictures.py:429
msgid "HD Picture file is not available"
msgstr "Fichier HD de la photo non disponible"

#: geovisio/utils/pictures.py:448
msgid "Picture derivates file are not available"
msgstr "Fichiers dérivés de la photo non disponibles"

#: geovisio/utils/pictures.py:465 geovisio/web/pictures.py:59
#: geovisio/web/pictures.py:108 geovisio/web/pictures.py:226
msgid "Unable to read picture on filesystem"
msgstr "Lecture de la photo sur le système de fichiers impossible"

#: geovisio/utils/sequences.py:371
msgid ""
"Sort by file date is not possible on this sequence (no file date "
"information available on pictures)"
msgstr ""
"Tri par date de fichier indisponible sur cette séquence (pas d'info de date "
"de fichier sur les photos)"

#: geovisio/utils/sequences.py:390
#, python-format
msgid ""
"Sort using %(sort)s is not possible on this sequence, picture %(pic)s is "
"missing mandatory metadata"
msgstr ""
"Tri par %(sort)s indisponible sur cette séquence, des attributs obligatoires "
"sont manquants sur la photo %(pic)s"

#: geovisio/utils/tokens.py:43
msgid "JWT token signature does not match"
msgstr "La signature du jeton JWT ne correspond pas"

#: geovisio/utils/tokens.py:59
msgid "Token does not exist anymore"
msgstr "Jeton indisponible"

#: geovisio/utils/tokens.py:63
msgid ""
"Token not yet claimed, this token cannot be used yet. Either claim this "
"token or generate a new one"
msgstr ""
"Jeton pas encore réclamé, il ne peut pas être utilisé pour l'instant. Vous "
"pouvez soit le réclamer (claim), soit en générer un nouveau"

#: geovisio/web/auth.py:62
msgid "Impossible to finish authentication flow"
msgstr "Impossible de finir le flux d'authentification"

#: geovisio/web/auth.py:66
msgid ""
"You can try to clear your cookies and retry. If the problem persists, "
"contact your instance administrator."
msgstr ""
"Vous pouvez tenter de supprimer vos cookies et réessayer. Si le problème "
"persiste, contactez l'administrateur de votre instance."

#: geovisio/web/collections.py:263
#, python-format
msgid "There is no collection created after %(d)s"
msgstr "Il n'y a pas de séquence créée après le %(d)s"

#: geovisio/web/collections.py:265
#, python-format
msgid "There is no collection created before %(d)s"
msgstr "Il n'y a pas de séquence créée avant le %(d)s"

#: geovisio/web/collections.py:371 geovisio/web/items.py:372
msgid "Collection doesn't exist"
msgstr "La collection n'existe pas"

#: geovisio/web/collections.py:431
msgid "Impossible to find a thumbnail for the collection"
msgstr "Impossible de trouver une miniature pour la séquence"

#: geovisio/web/collections.py:544 geovisio/web/items.py:1133
msgid ""
"Picture visibility parameter (visible) should be either unset, true or "
"false"
msgstr ""
"Le paramètre de visibilité de la photo (\"visible\") doit être soit vide, "
"\"true\" ou \"false\""

#: geovisio/web/collections.py:550
msgid ""
"Sequence title is not valid, should be a string with a max of 250 "
"characters"
msgstr ""
"Le titre de la séquence est invalide, ce doit être une chaîne de 250 "
"caractères maximum"

#: geovisio/web/collections.py:556
msgid "Sort order parameter is invalid"
msgstr "Le paramètre d'ordre de tri est invalide"

#: geovisio/web/collections.py:566
msgid ""
"Relative heading is not valid, should be an integer in degrees from -180 "
"to 180"
msgstr ""
"L'orientation relative est invalide, ce doit être un nombre entier de -180 à "
"180 degrés"

#: geovisio/web/collections.py:582
#, python-format
msgid "Sequence %(c)s wasn't found in database"
msgstr "La séquence %(c)s n'a pas été trouvée"

#: geovisio/web/collections.py:586 geovisio/web/collections.py:702
msgid "You're not authorized to edit this sequence"
msgstr "Vous n'avez pas la permission de modifier cette séquence"

#: geovisio/web/collections.py:595
#, python-format
msgid "Sequence %(c)s is in %(s)s state, its visibility can't be changed for now"
msgstr ""
"La séquence %(c)s est en état \"%(s)s\", sa visibilité ne peut pas être "
"changée pour l'instant"

#: geovisio/web/collections.py:698
#, python-format
msgid "Collection %(c)s wasn't found in database"
msgstr "La séquence %(c)s n'a pas été trouvée en base"

#: geovisio/web/collections.py:793
msgid "Sequence doesn't exists"
msgstr "La séquence n'existe pas"

#: geovisio/web/collections.py:938 geovisio/web/stac.py:340
#, python-format
msgid "Impossible to find user %(u)s"
msgstr "Impossible de trouver l'utilisateur %(u)s"

#: geovisio/web/collections.py:969 geovisio/web/stac.py:350
#, python-format
msgid "No data loaded for user %(u)s"
msgstr "Pas de données chargées pour l'utilisateur %(u)s"

#: geovisio/web/collections.py:971
msgid "No matching sequences found"
msgstr "Aucune séquence correspondante trouvée"

#: geovisio/web/items.py:335
msgid "limit parameter should be an integer between 1 and 10000"
msgstr ""
"Le paramètre \"limit\" doit être un nombre entier compris entre 1 et 10000"

#: geovisio/web/items.py:337
msgid "limit parameter should be a valid, positive integer (between 1 and 10000)"
msgstr ""
"Le paramètre \"limit\" doit être un nombre entier valide (entre 1 et 10000)"

#: geovisio/web/items.py:342
msgid "`startAfterRank` and `withPicture` are mutually exclusive parameters"
msgstr ""
"Les paramètres `startAfterRank` et `withPicture` ne peuvent être utilisés "
"ensemble"

#: geovisio/web/items.py:349
msgid "startAfterRank parameter should be a positive integer (starting from 1)"
msgstr ""
"Le paramètre \"startAfterRank\" doit être un nombre entier positif ("
"supérieur ou égal à 1)"

#: geovisio/web/items.py:351
msgid "startAfterRank parameter should be a valid, positive integer"
msgstr "Le paramètre \"startAfterRank\" doit être un nombre entier positif"

#: geovisio/web/items.py:377
#, python-format
msgid "No more items in this collection (last available rank is %(r)s)"
msgstr "Plus de photos dans cette séquence (dernier rang disponible : %(r)s)"

#: geovisio/web/items.py:386
#, python-format
msgid "Picture with id %(p)s does not exist"
msgstr "La photo avec l'ID %(p)s n'existe pas"

#: geovisio/web/items.py:670
msgid "Item doesn't exist"
msgstr "Cet élément n'existe pas"

#: geovisio/web/items.py:729
msgid "Search using POST method should have a JSON body"
msgstr "La recherche par méthode POST doit avoir un corps de requête en JSON"

#: geovisio/web/items.py:738
msgid "Parameter limit must be either empty or a number between 1 and 10000"
msgstr ""
"Le paramètre \"limit\" doit être soit vide, soit un nombre entre 1 et 10000"

#: geovisio/web/items.py:794
msgid ""
"Parameter place_fov_tolerance must be either empty or a number between 2 "
"and 180"
msgstr ""
"Le paramètre \"place_fov_tolerance\" doit être soit vide, soit un nombre "
"compris entre 2 et 180"

#: geovisio/web/items.py:816
msgid ""
"Parameter intersects should contain a valid GeoJSON Geometry (not a "
"Feature)"
msgstr ""
"Le paramètre \"intersects\" doit contenir une géométrie GeoJSON valide (pas "
"une \"Feature\")"

#: geovisio/web/items.py:832
msgid "Parameter ids should be a JSON array of strings"
msgstr "Le paramètres \"ids\" doit être une liste JSON de chaînes de caractères"

#: geovisio/web/items.py:844
msgid "Parameter collections should be a JSON array of strings"
msgstr ""
"Le paramètre \"collections\" doit être une liste JSON de chaînes de "
"caractères"

#: geovisio/web/items.py:855
msgid "Picture doesn't exist"
msgstr "La photo n'existe pas"

#: geovisio/web/items.py:956
msgid "Content type should be multipart/form-data"
msgstr "Le type de contenu (\"Content-type\") doit être \"multipart/form-data\""

#: geovisio/web/items.py:960
msgid "Missing \"position\" parameter"
msgstr "Paramètre \"position\" manquant"

#: geovisio/web/items.py:967
msgid "Position in sequence should be a positive integer"
msgstr "La position dans la séquence doit être un nombre entier positif"

#: geovisio/web/items.py:981
msgid ""
"Longitude cannot be overridden alone, override_latitude also needs to be "
"set"
msgstr ""
"La longitude ne peut pas être surchargée seule, \"override_latitude\" doit "
"aussi être renseigné"

#: geovisio/web/items.py:983
msgid ""
"Latitude cannot be overridden alone, override_longitude also needs to be "
"set"
msgstr ""
"La latitude ne peut pas être surchargée seule, \"override_longitude\" doit "
"aussi être renseigné"

#: geovisio/web/items.py:984
#, python-format
msgid "For parameter `override_longitude`, `%(v)s` is not a valid longitude"
msgstr "Le paramètre `override_longitude` a une valeur %(v)s invalide"

#: geovisio/web/items.py:985
#, python-format
msgid "For parameter `override_latitude`, `%(v)s` is not a valid latitude"
msgstr "Le paramètre `override_latitude` a une valeur %(v)s invalide"

#: geovisio/web/items.py:1004
msgid "Picture blur status should be either unset, true or false"
msgstr ""
"L'état de floutage de la photo (blur) doit être soit vide, \"true\" ou "
"\"false\""

#: geovisio/web/items.py:1008
msgid "No picture file was sent"
msgstr "Aucun fichier de photo n'a été envoyé"

#: geovisio/web/items.py:1014
msgid "Picture file is either missing or in an unsupported format (should be jpg)"
msgstr ""
"Le fichier photo est soit manquant, soit dans un format non-supporté (doit "
"être en JPEG)"

#: geovisio/web/items.py:1021
#, python-format
msgid "Sequence %(s)s wasn't found in database"
msgstr "La séquence %(s)s est introuvable en base"

#: geovisio/web/items.py:1052
msgid "Picture at given position already exist"
msgstr "Une photo à cette position existe déjà"

#: geovisio/web/items.py:1054
msgid "Impossible to parse picture metadata"
msgstr "Impossible de lire les métadonnées de la photo"

#: geovisio/web/items.py:1062
msgid "Picture wasn't correctly saved in filesystem"
msgstr ""
"La photo n'a pas été correctement enregistrée sur le système de fichiers"

#: geovisio/web/items.py:1145
msgid ""
"Heading is not valid, should be an integer in degrees from 0° to 360°. "
"North is 0°, East = 90°, South = 180° and West = 270°."
msgstr ""
"L'orientation (\"heading\") est invalide, ce doit être un nombre entier de 0 "
"à 360°. Le Nord est à 0°, l'Est à 90°, le Sud à 180° et l'Ouest à 270°."

#: geovisio/web/items.py:1160 geovisio/web/items.py:1251
#, python-format
msgid "Picture %(p)s wasn't found in database"
msgstr "La photo %(p)s est introuvable en base"

#: geovisio/web/items.py:1164 geovisio/web/items.py:1255
msgid "You're not authorized to edit this picture"
msgstr "Vous n'avez pas la permission de modifier cette photo"

#: geovisio/web/items.py:1174
#, python-format
msgid "Picture %(p)s is in %(s)s state, its visibility can't be changed for now"
msgstr ""
"La photo %(p)s est en état \"%(s)s\", sa visibilité ne peut pas être changée "
"pour l'instant"

#: geovisio/web/map.py:124
msgid "One of required parameter is empty"
msgstr "L'un des paramètres obligatoires est manquant"

#: geovisio/web/map.py:126
msgid "Tile format is invalid, should be either pbf or mvt"
msgstr "Le format de tuile est invalide, ce doit être pbf ou mvt"

#: geovisio/web/map.py:130 geovisio/web/map.py:132
msgid "X or Y parameter is out of bounds"
msgstr "Le paramètre X ou Y est hors limites"

#: geovisio/web/map.py:134
msgid "Z parameter is out of bounds (should be 0-15)"
msgstr "Le paramètre Z est hors limites (doit être entre 0 et 15)"

#: geovisio/web/map.py:145
msgid "Impossible to get tile"
msgstr "Impossible de récupérer la tuile"

#: geovisio/web/params.py:101
msgid "Parameter datetime should contain one or two dates"
msgstr "Le paramètre \"datetime\" doit contenir une ou deux dates"

#: geovisio/web/params.py:171
msgid ""
"Parameter bbox must contain valid longitude (-180 to 180) and latitude "
"(-90 to 90) values"
msgstr ""
"Le paramètre \"bbox\" doit contenir des valeurs valides de longitude (-180 à "
"180°) et de latitude (-90 à 90°)"

#: geovisio/web/params.py:176
msgid "Parameter bbox must be in format [minX, minY, maxX, maxY]"
msgstr "Le paramètre \"bbox\" doit être au format [minX, minY, maxX, maxY]"

#: geovisio/web/params.py:214
#, python-format
msgid "Parameter %(p)s must be coordinates in lat,lon format"
msgstr "Le paramètre \"%(p)s\" doit être une position au format lat,lon"

#: geovisio/web/params.py:219
#, python-format
msgid "Longitude in parameter %(p)s is not valid (should be between -180 and 180)"
msgstr ""
"La longitude dans le paramètre \"%(p)s\" est invalide (doit être comprise "
"entre -180 et 180°)"

#: geovisio/web/params.py:220
#, python-format
msgid "Latitude in parameter %(p)s is not valid (should be between -90 and 90)"
msgstr ""
"La latitude dans le paramètre \"%(p)s\" est invalide (doit être comprise "
"entre -90 et 90°)"

#: geovisio/web/params.py:243 geovisio/web/params.py:254
#, python-format
msgid ""
"Parameter %(p)s is invalid (should be a distance range in meters like "
"\"5-15\")"
msgstr ""
"Le paramètre \"%(p)s\" est invalide (doit être un intervalle de distance tel "
"que \"5-15\")"

#: geovisio/web/params.py:248
#, python-format
msgid "Parameter %(p)s has a min value greater than its max value"
msgstr ""
"Le paramètre \"%(p)s\" a une valeur minimale plus grande que sa valeur "
"maximale"

#: geovisio/web/params.py:321
#, python-format
msgid "Parameter %(p)s must be a valid list"
msgstr "Le paramètre \"%(p)s\" doit être une liste valide"

#: geovisio/web/params.py:360
msgid "Unsupported filter parameter"
msgstr "Paramètre de filtre non supporté"

#: geovisio/web/params.py:445
msgid "Unsupported sortby parameter: invalid column name"
msgstr ""
"Paramètre de tri \"sortby\" non supporté : le nom de colonne est invalide"

#: geovisio/web/params.py:453
msgid "Unsupported sortby parameter: syntax isn't correct"
msgstr "Paramètre de tri \"sortby\" invalide : la syntaxe n'est pas correcte"

#: geovisio/web/params.py:479
#, python-format
msgid "limit parameter should be a valid, positive integer (between 1 and %(v)s)"
msgstr ""
"Le paramètre \"limit\" doit être un nombre entier positif (entre 1 et %(v)s)"

#: geovisio/web/params.py:482
#, python-format
msgid "limit parameter should be an integer between 1 and %(v)s"
msgstr "Le paramètre \"limit\" doit être un nombre compris entre 1 et %(v)s"

#: geovisio/web/params.py:493
msgid "longitude needs to be between -180 and 180"
msgstr "La longitude doit être comprise entre -180 et 180°"

#: geovisio/web/params.py:503
msgid "latitude needs to be between -90 and 90"
msgstr "La latitude doit être comprise entre -90 et 90°"

#: geovisio/web/pictures.py:205
msgid "Tiles are not available for flat pictures"
msgstr "Les tuiles ne sont pas disponibles pour les photos classiques"

#: geovisio/web/pictures.py:210
msgid "Column parameter is invalid, should be an integer"
msgstr "Le paramètre \"column\" est invalide, ce doit être un nombre entier"

#: geovisio/web/pictures.py:213
msgid "Column parameter is invalid"
msgstr "Le paramètre \"column\" est invalide"

#: geovisio/web/pictures.py:218
msgid "Row parameter is invalid, should be an integer"
msgstr "Le paramètre \"row\" est invalide, ce doit être un nombre entier"

#: geovisio/web/pictures.py:221
msgid "Row parameter is invalid"
msgstr "Le paramètre \"row\" est invalide"

#: geovisio/web/rss.py:22
#, python-format
msgid "Sequence \"%(name)s\" by \"%(user)s\" was captured on %(date)s."
msgstr "La séquence \"%(name)s\" par \"%(user)s\" a été prise le %(date)s."

#: geovisio/web/rss.py:40
msgid "View on the map"
msgstr "Voir sur la carte"

#: geovisio/web/rss.py:40
msgid "JSON metadata"
msgstr "Métadonnées JSON"

#: geovisio/web/rss.py:49
msgid "GeoVisio collections"
msgstr "Séquences GeoVisio"

#: geovisio/web/rss.py:51
msgid "List of collections from this GeoVisio server"
msgstr "Liste des séquences de cette instance GeoVisio"

#: geovisio/web/tokens.py:101 geovisio/web/tokens.py:144
#: geovisio/web/tokens.py:232
msgid "Impossible to find token"
msgstr "Impossible de trouver le jeton"

#: geovisio/web/tokens.py:182
msgid "Impossible to generate a new token"
msgstr "Impossible de générer un nouveau jeton"

#: geovisio/web/tokens.py:237
msgid "Token already claimed by another account"
msgstr "Le jeton a déjà été associée à un autre compte utilisateur"

#: geovisio/web/users.py:82
msgid "Impossible to find user"
msgstr "Impossible de trouver l'utilisateur"

#: geovisio/web/users.py:158
msgid ""
"No search parameter given, you should provide `q=<pattern>` as query "
"parameter"
msgstr ""
"Aucun paramètre de recherche fourni, vous devez renseigner `q=<motif>` comme "
"valeur de recherche"

#: geovisio/web/utils.py:51
msgid "No default account defined, please contact your instance administrator"
msgstr ""
"Aucun compte par défaut défini, merci de contacter l'administrateur de votre "
"instance"

#: geovisio/web/upload_set.py:461
msgid "The item has already been added to this upload set"
msgstr "L'item a déjà été ajouté à cet UploadSet"

#: geovisio/web/upload_set.py:430
msgid "You're not authorized to add picture to this collection"
msgstr "Vous n'avez pas la permission d'ajouter une photo dans cette séquence"

#: geovisio/web/upload_set.py:434
msgid "The upload set is already completed, files cannot be pushed to it"
msgstr ""
"L'UploadSet est déjà complet, aucun fichier supplémentaire ne peut être "
"ajouté"

#: geovisio/web/upload_set.py:426 geovisio/web/upload_set.py:651
msgid "UploadSet {u} does not exist"
msgstr "L'UploadSet {u} n'existe pas"

#: geovisio/web/upload_set.py:147
msgid "Parameter for creating an UploadSet should be a valid JSON"
msgstr "Le paramètre pour créer un UploadSet doit être un JSON valide"

#: geovisio/web/upload_set.py:193 geovisio/web/upload_set.py:674
msgid "UploadSet doesn't exist"
msgstr "L'UploadSet n'existe pas"

#: geovisio/web/upload_set.py:241 geovisio/web/upload_set.py:340
msgid "Impossible to parse parameters"
msgstr "Lecture des paramètres impossible"

#: geovisio/web/upload_set.py:279
msgid ""
"Parameter `override_capture_time` is not a valid datetime, it should be an "
"iso formated datetime (like '2017-07-21T17:32:28Z')."
msgstr ""
"Le paramètre `override_capture_time`n'est pas un horodatage valide, il "
"devrait être au format ISO (exemple '2017-07-21T17:32:28Z')."

#: geovisio/web/upload_set.py:285
msgid "For parameter `override_longitude`, `{value}` is not a valid longitude"
msgstr "La valeur `{value}` du paramètre `override_longitude` n'est pas valide"

#: geovisio/web/upload_set.py:290
msgid "For parameter `override_latitude`, `{value}` is not a valid longitude"
msgstr "La valeur `{value}` du paramètre `override_latitude` n'est pas valide"

#: geovisio/web/upload_set.py:329
msgid "No file was sent"
msgstr "Aucun fichier n'a été envoyé"

#: geovisio/web/upload_set.py:145
msgid "Impossible to create an UploadSet"
msgstr "Création d'un UploadSet impossible"

#: geovisio/web/upload_set.py:466
msgid "The same picture has already been sent in a past upload"
msgstr "Cette même photo a déjà été envoyée par le passé"

#: geovisio/web/upload_set.py:554
msgid "UploadSet doesn't exists"
msgstr "L'UploadSet n'existe pas"

#: geovisio/web/upload_set.py:655
msgid "You're not authorized to complete this upload set"
msgstr "Vous n'avez pas la permission de finaliser cet UploadSet"

#: geovisio/web/upload_set.py:660
msgid ""
"The upload set is already completed, cannot complete it several times for "
"the moment"
msgstr ""
"Cet UploadSet est déjà finalisé, il n'est pas permis de le finaliser "
"plusieurs fois pour l'instant"

#: geovisio/web/upload_set.py:428 geovisio/web/upload_set.py:653
#, python-format
msgid "UploadSet %(u)s does not exist"
msgstr "L'UploadSet %(u)s n'existe pas"

#: geovisio/web/upload_set.py:460
msgid "You're not authorized to add picture to this upload set"
msgstr "Vous n'avez pas la permission d'ajouter des photos à cet Upload Set"

#: geovisio/utils/upload_set.py:148
msgid ""
"The picture is too similar to another one (nearby and taken almost at the "
"same time)"
msgstr ""
"La photo est trop similaire à une autre (trop proche et prise presque à la "
"même heure)"

#: geovisio/utils/upload_set.py:150
msgid "The sent file is not a valid JPEG"
msgstr "Le fichier envoyé n'est pas une image JPEG valide"

#: geovisio/utils/upload_set.py:152
msgid ""
"The picture has invalid EXIF or XMP metadata, making it impossible to use"
msgstr ""
"La photo a des métadonnées EXIF ou XMP invalides, la rendant impossible à "
"utiliser"

#: geovisio/web/reports.py:89 geovisio/web/reports.py:99
msgid "Impossible to create a Report"
msgstr "Impossible de créer un signalement"

#: geovisio/web/reports.py:91
msgid "Parameter for creating a Report should be a valid JSON"
msgstr ""
"Les paramètres pour créer un signalement doivent être sous forme d'un JSON "
"valide"

#: geovisio/web/upload_set.py:607
msgid ""
"Impossible to open file as image. The only supported image format is jpg."
msgstr ""
"Impossible d'ouvrir le fichier en tant qu'image. Le seul format accepté est "
"le JPEG."

#: geovisio/utils/upload_set.py:154
msgid "Something went very wrong, but not due to the picture itself"
msgstr "Quelque chose s'est mal passé, mais pas à cause de l'image"

#: geovisio/web/items.py:1048
#, python-format
msgid "Collection %(s)s wasn't found in database"
msgstr "La séquence %(s)s n'a pas été trouvée en base"

#: geovisio/web/items.py:1057
msgid "The collection has been deleted, impossible to add pictures to it"
msgstr ""
"La séquence a été supprimée, il n'est pas possible d'y ajouter des images"

#: geovisio/web/reports.py:144
msgid "Only authenticated users can access reports"
msgstr "Seules les personnes authentifiées peuvent accéder aux signalements"

#: geovisio/web/reports.py:148 geovisio/web/reports.py:266
msgid "Report doesn't exist"
msgstr "Le signalement n'existe pas"

#: geovisio/web/reports.py:157
msgid "You're not authorized to access this report"
msgstr "Vous n'avez pas l'autorisation d'accéder à ce signalement"

#: geovisio/web/reports.py:277
msgid "You're not authorized to edit this Report"
msgstr "Vous n'avez pas l'autorisation d'éditer ce signalement"

#: geovisio/web/reports.py:284
msgid "Impossible to edit the Report"
msgstr "Impossible d'éditer le signalement"

#: geovisio/web/reports.py:286
msgid "Parameter for editing the Report should be a valid JSON"
msgstr ""
"Les paramètres pour éditer le signalement doivent êtres sous forme d'un JSON "
"valide"

#: geovisio/web/reports.py:352
msgid "You're not authorized to list reports"
msgstr "Vous n'avez pas l'autorisation de lister les signalements"

#: geovisio/web/upload_set.py:209
msgid "You're not authorized to list pictures in this upload set"
msgstr "Vous n'avez pas l'autorisation de lister les photos dans cet Upload Set"

#: geovisio/utils/excluded_areas.py:82
msgid "Impossible to find excluded area"
msgstr "Impossible de trouver une zone exclue"

#: geovisio/web/excluded_areas.py:134
msgid "You must be logged-in as admin to access all excluded areas"
msgstr ""
"Vous devez vous identifier en admin pour accéder à toutes les zones exclues"

#: geovisio/web/excluded_areas.py:136
msgid "You're not authorized to access all excluded areas"
msgstr "Vous n'êtes pas autorisé à accéder à toutes les zones exclues"

#: geovisio/web/excluded_areas.py:173 geovisio/web/excluded_areas.py:183
#: geovisio/web/excluded_areas.py:337 geovisio/web/excluded_areas.py:344
msgid "Impossible to create an Excluded Area"
msgstr "Impossible de créer une zone exclue"

#: geovisio/web/excluded_areas.py:175 geovisio/web/excluded_areas.py:339
msgid "Parameter for creating an Excluded Area should be a valid JSON"
msgstr "Les paramètres pour créer une zone exclue doivent être un JSON valide"

#: geovisio/web/excluded_areas.py:178 geovisio/web/excluded_areas.py:236
msgid "You must be logged-in as admin to edit excluded areas"
msgstr "Vous devez être identifié en admin pour éditer les zones exclues"

#: geovisio/web/excluded_areas.py:231 geovisio/web/excluded_areas.py:243
msgid "Impossible to replace all Excluded Areas"
msgstr "Impossible de remplacer toutes les zones exclues"

#: geovisio/web/items.py:1091 geovisio/web/upload_set.py:622
msgid "Picture has invalid metadata"
msgstr "L'image contient un metadata invalide"

#: geovisio/web/excluded_areas.py:233
msgid "Parameter for replacing all Excluded Areas should be a valid JSON"
msgstr ""
"Le paramètre pour remplacer toutes les Zones Exclues doit être un JSON valide"

#: geovisio/web/excluded_areas.py:273
msgid "You must be logged-in as admin to delete excluded areas"
msgstr ""
"Vous devez être connecté en tant qu'administrateur pour supprimer des zones "
"exclues"

#: geovisio/web/upload_set.py:763
msgid "You're not authorized to delete this upload set"
msgstr "Vous n'avez pas l'autorisation de supprimer cet UploadSet"

#: geovisio/utils/upload_set.py:587
msgid ""
"A different picture with the same name has already been added to this "
"uploadset"
msgstr ""
"Une photo différente ayant le même nom a déjà été ajoutée à cet uploadset"

#: geovisio/web/items.py:1181
#, python-format
msgid "For parameter `longitude`, `%(v)s` is not a valid longitude"
msgstr "Pour le paramètre `longitude`, `%(v)s` n'est pas une longitude correcte"

#: geovisio/web/items.py:1186
#, python-format
msgid "For parameter `latitude`, `%(v)s` is not a valid latitude"
msgstr "Pour le paramètre `latitude`, `%(v)s`n'est pas une correct latitude"

#: geovisio/web/items.py:1173
msgid ""
"Parameter `capture_time` is not a valid datetime, it should be an iso "
"formated datetime (like '2017-07-21T17:32:28Z')."
msgstr ""
"Le paramètre`capture_time` n'est pas un correct datetime, il est préférable "
"d'utiliser le format ISO (comme '2017-07-21T17:32:28Z')."

#: geovisio/web/items.py:1191
msgid "Longitude cannot be overridden alone, latitude also needs to be set"
msgstr ""
"La longitude ne peut pas être renseignée seule, la latitude doit être "
"également renseignée"

#: geovisio/web/items.py:1193
msgid "Latitude cannot be overridden alone, longitude also needs to be set"
msgstr ""
"La latitude ne peut pas être indiquée seule, la longitude doit être "
"également indiquée"

#: geovisio/utils/auth.py:283
#, python-format
msgid ""
"You need to accept the terms of service before uploading any pictures. You "
"can do so by validating them here: %(url)s"
msgstr ""
"Vous devez accepter les conditions d'utilisation du service avant d'uploader "
"des images. Vous pouvez le faire en les validant ici : %(url)s"

#: geovisio/web/collections.py:697
msgid ""
"You're not authorized to edit those fields for this sequence. Only the owner "
"can change the visibility and the title"
msgstr ""
"Vous n'êtes pas autorisé à modifier ces champs pour cette séquence. Seul le "
"propriétaire peut modifier la visibilité et le titre"

#: geovisio/web/collections.py:707
msgid ""
"You're not authorized to edit this sequence, collaborative editing is not "
"allowed"
msgstr ""
"Vous n'êtes pas autorisé à éditer cette séquence, l'édition collaborative "
"n'est pas autorisée"

#: geovisio/web/items.py:1318
msgid ""
"You're not authorized to edit the visibility of this picture. Only the owner "
"can change this."
msgstr ""
"Vous n'êtes pas autorisé à éditer la visibilité de cette photo. Seulement le "
"dépositaire peut la changer."

#: geovisio/web/items.py:1163
msgid "There is already a picture with the same index in the sequence"
msgstr "Une photo existe déjà à cette position (index) dans cette séquence"

#: geovisio/web/items.py:1361
msgid ""
"You're not authorized to edit this picture, collaborative editing is not "
"allowed"
msgstr ""
"Vous n'avez pas les droits suffisants pour modifier cette photo, l'édition "
"collaborative est désactivée"

#: geovisio/web/params.py:468
msgid "Unsupported sortby parameter: invalid field"
msgstr "Paramètre \"sortby\" non-géré : champ invalide"

#: geovisio/web/annotations.py:74
msgid "Impossible to create an annotation"
msgstr "Impossible de créer une annotation"

#: geovisio/web/annotations.py:76
msgid "Parameter for creating an annotation should be a valid JSON"
msgstr "Le paramètre pour créer une annotation doit être un JSON valide"

#: geovisio/web/annotations.py:134 geovisio/web/annotations.py:208
#, python-format
msgid "Annotation %(p)s not found"
msgstr "Annotation %(p)s introuvable"

#: geovisio/web/annotations.py:202
msgid "Parameter for updating an annotation should be a valid JSON"
msgstr "Le paramètre pour actualiser une annotation doit être un JSON valide"

#: geovisio/web/collections.py:926
msgid "CSV export does not support pagination"
msgstr "L'export CSV ne gère pas la pagination"

#: geovisio/web/collections.py:928
msgid "CSV export does not support filters"
msgstr "L'export CSV ne gère pas les filtres"

#: geovisio/web/pages.py:127 geovisio/web/pages.py:236
#, python-format
msgid "Page not available in language %(l)s"
msgstr "La page n'est pas disponible dans la langue %(l)s"

#: geovisio/web/pages.py:178
msgid "Page content must be HTML (with Content-Type: text/html header set)"
msgstr ""
"Le contenu de la page doit être du HTML (avec l'en-tête Content-Type : text/"
"html)"

#: geovisio/web/pages.py:192
msgid "Could not update page content"
msgstr "Impossible de modifier le contenu de la page"

#: geovisio/web/pages.py:238
msgid "Could not delete page content"
msgstr "Impossible de supprimer le contenu de la page"

#: geovisio/web/upload_set.py:245
msgid "Impossible to update the UploadSet"
msgstr "Impossible de modifier l'Upload Set"

#: geovisio/web/upload_set.py:247
msgid "Parameter for updating an UploadSet should be a valid JSON"
msgstr "Le paramètre pour modifier un Upload Set doit être un JSON valide"

#: geovisio/web/upload_set.py:255
msgid "You are not allowed to update this upload set"
msgstr "Vous n'avez pas les droits suffisants pour modifier cet upload set"

#: geovisio/web/annotations.py:200
msgid "Impossible to patch annotation, invalid parameters"
msgstr "Impossible de modifier l'annotation, les paramètres sont invalides"

#: geovisio/web/collections.py:935
msgid "CSV export does not support sorting by anything but creation date"
msgstr "L'export CSV gère uniquement le tri par date de création"

#: geovisio/web/pages.py:45
msgid "Page name is not recognized"
msgstr "Nom de page non reconnu"

#: geovisio/web/pages.py:176 geovisio/web/pages.py:230
msgid "You must be logged-in as admin to edit pages"
msgstr "Vous devez être connecté en tant qu'admin pour éditer les pages"
