# Translations template for PROJECT.
# Copyright (C) 2024 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2024.
#
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2024-09-17 14:45+0200\n"
"PO-Revision-Date: 2025-02-27 12:32+0000\n"
"Last-Translator: PanierAvide <adrien@pavie.info>\n"
"Language-Team: Hungarian <http://weblate.panoramax.xyz/projects/panoramax/"
"api/hu/>\n"
"Language: hu\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"X-Generator: Weblate 5.4.3\n"
"Generated-By: Babel 2.16.0\n"

#: geovisio/templates/main.html:45
msgid "Simple 360° geolocated pictures hosting"
msgstr "Földrajzilag lokalizált 360°-os képek egyszerű tárolása"

#: geovisio/templates/main.html:47
msgid "Full page version"
msgstr "Teljes oldalas változat"

#: geovisio/templates/main.html:51
msgid "Viewer"
msgstr "Nézegető"

#: geovisio/templates/main.html:52
msgid "Embed pre-configured viewer"
msgstr "Előre konfigurált nézegető beágyazása"

#: geovisio/templates/main.html:53
msgid "Easiest way to have a working GeoVisio viewer on your website"
msgstr ""
"Ez a legegyszerűbb módja annak, hogy működő GeoVisio nézegető legyen a "
"weboldalán"

#: geovisio/templates/main.html:59
msgid "Use JS library"
msgstr "JS könyvtár használata"

#: geovisio/templates/main.html:60
msgid "A completely configurable viewer for your website"
msgstr "Teljesen konfigurálható nézegető, a te weboldaladhoz is"

#: geovisio/templates/main.html:82
msgid "Links"
msgstr "Linkek"

#: geovisio/templates/main.html:84
msgid "Pictures viewer"
msgstr "Képnézegető"

#: geovisio/templates/main.html:86
msgid "API docs"
msgstr "API dokumentáció"

#: geovisio/templates/main.html:88
msgid "JS library docs"
msgstr "JS könyvtár dokumentáció"

#: geovisio/templates/main.html:90
msgid "Repositories"
msgstr "Tárházak"

#: geovisio/templates/viewer.html:22
msgid "You need to enable JavaScript to run this app."
msgstr "Az alkalmazás futtatásához engedélyezned kell a JavaScriptet."

#: geovisio/utils/auth.py:201
msgid "Authentication is mandatory"
msgstr "A hitelesítés kötelező"

#: geovisio/utils/auth.py:330
msgid "Only Bearer token are supported"
msgstr "Csak a Bearer token támogatott"

#: geovisio/utils/excluded_areas.py:82
msgid "Impossible to find excluded area"
msgstr "Nem lehet megtalálni a kizárt területet"

#: geovisio/utils/pictures.py:305
#, python-format
msgid ""
"Invalid '%(format)s' format for image, only the following formats are "
"available: %(allowed_formats)s"
msgstr ""
"Érvénytelen '%(format)s' képformátumú; csak a következő formátumok működnek: "
"%(allowed_formats)s"

#: geovisio/utils/pictures.py:419
msgid "Picture can't be found, you may check its ID"
msgstr "A kép nem található, megpróbálhatod ellenőrizni az azonosítóját (ID)"

#: geovisio/utils/pictures.py:422
msgid "Picture is not available (either hidden by admin or processing)"
msgstr ""
"A kép nem elérhető (vagy a rendszergazda elrejtette, vagy éppen feldolgozás "
"alatt áll)"

#: geovisio/utils/pictures.py:430
msgid "HD Picture file is not available"
msgstr "A nagy felbontású (HD) képfájl nem elérhető"

#: geovisio/utils/pictures.py:449
msgid "Picture derivates file are not available"
msgstr "A képszármazékfájl nem elérhető"

#: geovisio/utils/pictures.py:466 geovisio/web/pictures.py:55
#: geovisio/web/pictures.py:100 geovisio/web/pictures.py:210
msgid "Unable to read picture on filesystem"
msgstr "A fájlrendszerben a kép nem olvasható"

#: geovisio/utils/reports.py:142 geovisio/utils/upload_set.py:352
#: geovisio/web/params.py:359
msgid "Unsupported filter parameter"
msgstr "Nem támogatott szűrő (filter) paraméter"

#: geovisio/utils/sequences.py:376
msgid ""
"Sort by file date is not possible on this sequence (no file date "
"information available on pictures)"
msgstr ""
"Ebben a sorozatban nem lehet a fájlokat dátum szerint sorba rendezni (a "
"képeken nem érhető el a fájl dátumára vonatkozó adat)"

#: geovisio/utils/sequences.py:395
#, python-format
msgid ""
"Sort using %(sort)s is not possible on this sequence, picture %(pic)s is "
"missing mandatory metadata"
msgstr ""
"A %(sort)s szerinti sorba rendezés nem lehetséges ebben a sorozatban, az "
"%(pic)s képről hiányoznak a kötelező metaadatok"

#: geovisio/utils/sequences.py:585 geovisio/web/collections.py:620
#, python-format
msgid "Collection %(c)s wasn't found in database"
msgstr "%(c)s gyűjtemény nem található az adatbázisban"

#: geovisio/utils/tokens.py:43
msgid "JWT token signature does not match"
msgstr "A JWT token aláírása nem egyezik"

#: geovisio/utils/tokens.py:57
msgid "Token does not exist anymore"
msgstr "Ez a token már nem létezik"

#: geovisio/utils/tokens.py:61
msgid ""
"Token not yet claimed, this token cannot be used yet. Either claim this "
"token or generate a new one"
msgstr ""
"Ezt a tokent még nem igényelték meg, ezért még nem használható. Igényelje "
"meg, vagy generáljon egy újat"

#: geovisio/utils/upload_set.py:158
msgid ""
"The picture is too similar to another one (nearby and taken almost at the"
" same time)"
msgstr ""
"A kép túlságosan hasonlít egy másikhoz (közel vannak egymáshoz, és szinte "
"azonos időben készültek)"

#: geovisio/utils/upload_set.py:161
msgid "The sent file is not a valid JPEG"
msgstr "A beküldött fájl nem érvényes JPEG"

#: geovisio/utils/upload_set.py:164
msgid "The picture has invalid EXIF or XMP metadata, making it impossible to use"
msgstr "Érvénytelenek a kép EXIF vagy XMP metaadatai, így a kép nem használható"

#: geovisio/utils/upload_set.py:167
msgid "Something went very wrong, but not due to the picture itself"
msgstr "Valami nagyon félresikerült, de nem a kép miatt"

#: geovisio/web/auth.py:61
msgid "Impossible to finish authentication flow"
msgstr "Nem lehet befejezni a hitelesítési folyamatot"

#: geovisio/web/auth.py:65
msgid ""
"You can try to clear your cookies and retry. If the problem persists, "
"contact your instance administrator."
msgstr ""
"Megpróbálhatja törölni a cookie-kat, és újra elindítani a folyamatot. Ha a "
"probléma továbbra is fennáll, lépjen kapcsolatba a Panoramax-példány "
"rendszergazdájával."

#: geovisio/web/collections.py:291
#, python-format
msgid "There is no collection created after %(d)s"
msgstr "%(d)s után nem jött létre gyűjtemény"

#: geovisio/web/collections.py:293
#, python-format
msgid "There is no collection created before %(d)s"
msgstr "%(d)s előtt nem jött létre gyűjtemény"

#: geovisio/web/collections.py:401 geovisio/web/items.py:393
msgid "Collection doesn't exist"
msgstr "A gyűjtemény nem létezik"

#: geovisio/web/collections.py:460
msgid "Impossible to find a thumbnail for the collection"
msgstr "Nem lehet megtalálni a gyűjtemény bélyegképét"

#: geovisio/web/collections.py:580 geovisio/web/items.py:1170
msgid ""
"Picture visibility parameter (visible) should be either unset, true or "
"false"
msgstr ""
"A kép láthatósági paraméterének (visible) lehetséges értékei: nem "
"beállított, igaz vagy hamis (unset, true, false)"

#: geovisio/web/collections.py:586
msgid ""
"Sequence title is not valid, should be a string with a max of 250 "
"characters"
msgstr ""
"A sorozat címe nem érvényes: egy legfeljebb 250 darabból álló "
"karakterláncnak kell lennie"

#: geovisio/web/collections.py:592
msgid "Sort order parameter is invalid"
msgstr "A sorba rendezés (order) paramétere érvénytelen"

#: geovisio/web/collections.py:603
msgid ""
"Relative heading is not valid, should be an integer in degrees from -180 "
"to 180"
msgstr ""
"A relatív irány nem érvényes, egész számnak kell lennie -180 és 180 fok "
"között"

#: geovisio/web/collections.py:624
msgid "You're not authorized to edit this sequence"
msgstr "Nincs jogosultságod a sorozat szerkesztésére"

#: geovisio/web/collections.py:633
#, python-format
msgid "Sequence %(c)s is in %(s)s state, its visibility can't be changed for now"
msgstr ""
"%(c)s sorozat állapota %(s)s, ezért láthatósága egyelőre nem módosítható"

#: geovisio/web/collections.py:768
#, fuzzy
msgid "Sequence doesn't exists"
msgstr "A sorozat nem létezik"

#: geovisio/web/collections.py:913 geovisio/web/stac.py:349
#, python-format
msgid "Impossible to find user %(u)s"
msgstr "%(u)s felhasználót nem lehet megtalálni"

#: geovisio/web/collections.py:944 geovisio/web/stac.py:359
#, python-format
msgid "No data loaded for user %(u)s"
msgstr "%(u)s felhasználónak nincs betöltött adata"

#: geovisio/web/collections.py:946
msgid "No matching sequences found"
msgstr "Nem található megfelelő sorozat"

#: geovisio/web/excluded_areas.py:134
msgid "You must be logged-in as admin to access all excluded areas"
msgstr ""
"Rendszergazdaként kell bejelentkezned, hogy az összes kizárt területhez "
"hozzáférj"

#: geovisio/web/excluded_areas.py:136
msgid "You're not authorized to access all excluded areas"
msgstr "Nincs jogosultságod az összes kizárt területhez hozzáférni"

#: geovisio/web/excluded_areas.py:173 geovisio/web/excluded_areas.py:183
#: geovisio/web/excluded_areas.py:337 geovisio/web/excluded_areas.py:344
msgid "Impossible to create an Excluded Area"
msgstr "Nem lehet létrehozni kizárt területet"

#: geovisio/web/excluded_areas.py:175 geovisio/web/excluded_areas.py:339
msgid "Parameter for creating an Excluded Area should be a valid JSON"
msgstr ""
"A kizárt terület (Excluded Area) létrehozásához használt paraméternek "
"érvényes JSON-nak kell lennie"

#: geovisio/web/excluded_areas.py:178 geovisio/web/excluded_areas.py:236
msgid "You must be logged-in as admin to edit excluded areas"
msgstr "Kizárt terület szerkesztéséhez rendszergazdaként kell bejelentkezned"

#: geovisio/web/excluded_areas.py:231 geovisio/web/excluded_areas.py:243
msgid "Impossible to replace all Excluded Areas"
msgstr "Nem lehet az összes kizárt területet helyettesíteni"

#: geovisio/web/excluded_areas.py:233
msgid "Parameter for replacing all Excluded Areas should be a valid JSON"
msgstr ""
"Az összes kizárt terület (Excluded Area) cseréjére szolgáló paraméternek "
"érvényes JSON-nak kell lennie"

#: geovisio/web/excluded_areas.py:273
msgid "You must be logged-in as admin to delete excluded areas"
msgstr "Kizárt terület törléséhez rendszergazdaként kell bejelentkezned"

#: geovisio/web/items.py:356
msgid "limit parameter should be an integer between 1 and 10000"
msgstr ""
"a korlátozó (limit) paraméternek 1 és 10000 közötti egész számnak kell lennie"

#: geovisio/web/items.py:358
msgid "limit parameter should be a valid, positive integer (between 1 and 10000)"
msgstr ""
"a korlátozó (limit) paraméternek 1 és 10000 közötti érvényes pozitív egész "
"számnak kell lennie"

#: geovisio/web/items.py:363
msgid "`startAfterRank` and `withPicture` are mutually exclusive parameters"
msgstr ""
"a `startAfterRank` és a `withPicture` egymást kölcsönösen kizáró paraméter"

#: geovisio/web/items.py:370
msgid "startAfterRank parameter should be a positive integer (starting from 1)"
msgstr ""
"a `startAfterRank` paraméternek (1-től kezdődő) pozitív egész számnak kell "
"lennie"

#: geovisio/web/items.py:372
msgid "startAfterRank parameter should be a valid, positive integer"
msgstr ""
"a `startAfterRank` paraméternek érvényes, pozitív egész számnak kell lennie"

#: geovisio/web/items.py:399
#, python-format
msgid "No more items in this collection (last available rank is %(r)s)"
msgstr "Nincs több elem a gyűjteményben (az utolsó elérhető rangsorhely %(r)s)"

#: geovisio/web/items.py:409
#, fuzzy, python-format
msgid "Picture with id %(p)s does not exist"
msgstr "Nincs %(p)s azonosítójú kép"

#: geovisio/web/items.py:695
msgid "Item doesn't exist"
msgstr "Az elem nem létezik"

#: geovisio/web/items.py:754
msgid "Search using POST method should have a JSON body"
msgstr "A POST módszerrel történő keresésnek JSON testtel kell rendelkeznie"

#: geovisio/web/items.py:763
msgid "Parameter limit must be either empty or a number between 1 and 10000"
msgstr ""
"A `limit` paraméternek üresnek vagy 1 és 10000 közötti számnak kell lennie"

#: geovisio/web/items.py:819
msgid ""
"Parameter place_fov_tolerance must be either empty or a number between 2 "
"and 180"
msgstr ""
"A `place_fov_tolerance` paraméternek üresnek vagy 2 és 180 közötti számnak "
"kell lennie"

#: geovisio/web/items.py:841
msgid ""
"Parameter intersects should contain a valid GeoJSON Geometry (not a "
"Feature)"
msgstr ""
"Az `intersects` paraméternek érvényes GeoJSON alakzatot kell tartalmaznia ("
"nem Feature-t)"

#: geovisio/web/items.py:857
msgid "Parameter ids should be a JSON array of strings"
msgstr "Az `ids` paraméternek karakterláncból álló JSON tömbnek kell lennie"

#: geovisio/web/items.py:869
msgid "Parameter collections should be a JSON array of strings"
msgstr ""
"A `collections` (gyűjtemények) paraméternek karakterláncból álló JSON "
"tömbnek kell lennie"

#: geovisio/web/items.py:880
msgid "Picture doesn't exist"
msgstr "A kép nem létezik"

#: geovisio/web/items.py:983 geovisio/web/upload_set.py:527
msgid "Content type should be multipart/form-data"
msgstr ""
"A tartalom típusának (content type) multipart/form-data típusúnak kell lennie"

#: geovisio/web/items.py:987
msgid "Missing \"position\" parameter"
msgstr "Hiányzó `position` paraméter"

#: geovisio/web/items.py:994
msgid "Position in sequence should be a positive integer"
msgstr ""
"A sorozatban elfoglalt pozíciónak (position) pozitív egész számnak kell "
"lennie"

#: geovisio/web/items.py:1008 geovisio/web/upload_set.py:336
msgid ""
"Longitude cannot be overridden alone, override_latitude also needs to be "
"set"
msgstr ""
"A földrajzi hosszúságot (longitude) önmagában nem lehet felülbírálni, hanem "
"be kell állítani az override_latitude értéket is"

#: geovisio/web/items.py:1010 geovisio/web/upload_set.py:338
msgid ""
"Latitude cannot be overridden alone, override_longitude also needs to be "
"set"
msgstr ""
"A földrajzi szélességet (latitude) önmagában nem lehet felülbírálni, hanem "
"be kell állítani az override_longitude értéket is"

#: geovisio/web/items.py:1011 geovisio/web/upload_set.py:311
#, python-format
msgid "For parameter `override_longitude`, `%(v)s` is not a valid longitude"
msgstr ""
"Az `override_longitude` paraméternél `%(v)s` nem érvényes hosszúsági fok"

#: geovisio/web/items.py:1012 geovisio/web/upload_set.py:316
#, python-format
msgid "For parameter `override_latitude`, `%(v)s` is not a valid latitude"
msgstr "Az `override_latitude` paraméternél `%(v)s` nem érvényes szélességi fok"

#: geovisio/web/items.py:1031
msgid "Picture blur status should be either unset, true or false"
msgstr ""
"A kép elhomályosításának állapota (blur status) csak nem beállított, igaz "
"vagy hamis lehet (unset, true, false)"

#: geovisio/web/items.py:1035
msgid "No picture file was sent"
msgstr "Nem lett elküldve képfájl"

#: geovisio/web/items.py:1041 geovisio/web/upload_set.py:377
msgid "Picture file is either missing or in an unsupported format (should be jpg)"
msgstr ""
"A képfájl vagy hiányzik, vagy nem támogatott formátumú (jpg-nek kell lennie)"

#: geovisio/web/items.py:1048
#, python-format
msgid "Collection %(s)s wasn't found in database"
msgstr "A %(s)s gyűjtemény nem található az adatbázisban"

#: geovisio/web/items.py:1052
msgid "You're not authorized to add picture to this collection"
msgstr "Nincs jogosultságod ehhez a gyűjteményhez képet adni"

#: geovisio/web/items.py:1057
msgid "The collection has been deleted, impossible to add pictures to it"
msgstr "A gyűjteményt törölték, nem lehet képet hozzáadni hozzá"

#: geovisio/web/items.py:1087
msgid "Picture at given position already exist"
msgstr "Az adott pozíciónál már van kép"

#: geovisio/web/items.py:1089 geovisio/web/upload_set.py:615
msgid "Impossible to parse picture metadata"
msgstr "Nem lehet elemezni a kép metaadatait"

#: geovisio/web/items.py:1091 geovisio/web/upload_set.py:622
msgid "Picture has invalid metadata"
msgstr "Érvénytelenek a kép metaadatai"

#: geovisio/web/items.py:1099 geovisio/web/upload_set.py:648
msgid "Picture wasn't correctly saved in filesystem"
msgstr "A kép nem megfelelően lett elmentve a fájlrendszerbe"

#: geovisio/web/items.py:1182
msgid ""
"Heading is not valid, should be an integer in degrees from 0° to 360°. "
"North is 0°, East = 90°, South = 180° and West = 270°."
msgstr ""
"Az irány nem érvényes, 0° és 360° közötti egész számnak kell lennie. Észak 0°"
", kelet 90°, dél 180°, nyugat pedig 270°."

#: geovisio/web/items.py:1199 geovisio/web/items.py:1290
#, python-format
msgid "Picture %(p)s wasn't found in database"
msgstr "A %(p)s kép nem található az adatbázisban"

#: geovisio/web/items.py:1203 geovisio/web/items.py:1294
msgid "You're not authorized to edit this picture"
msgstr "Nincs jogosultságod a kép szerkesztéséhez"

#: geovisio/web/items.py:1213
#, python-format
msgid "Picture %(p)s is in %(s)s state, its visibility can't be changed for now"
msgstr "A %(p)s kép %(s)s állapotú, láthatósága ezért egyelőre nem módosítható"

#: geovisio/web/map.py:124
msgid "One of required parameter is empty"
msgstr "Az egyik szükséges paraméter üres"

#: geovisio/web/map.py:126
msgid "Tile format is invalid, should be either pbf or mvt"
msgstr "A csempeformátum érvénytelen, pbf vagy mvt formátumúnak kell lennie"

#: geovisio/web/map.py:130 geovisio/web/map.py:132
msgid "X or Y parameter is out of bounds"
msgstr "Az X vagy az Y paraméter kívül van a határértéken"

#: geovisio/web/map.py:134
msgid "Z parameter is out of bounds (should be 0-15)"
msgstr "A Z paraméter kívül van a határértéken (0-15 lehet)"

#: geovisio/web/map.py:145
msgid "Impossible to get tile"
msgstr "Nem lehet letölteni a csempét"

#: geovisio/web/params.py:101
msgid "Parameter datetime should contain one or two dates"
msgstr "A `datetime` paraméternek tartalmaznia kell egy vagy két dátumot"

#: geovisio/web/params.py:171
msgid ""
"Parameter bbox must contain valid longitude (-180 to 180) and latitude "
"(-90 to 90) values"
msgstr ""
"A `bbox` paraméternek érvényes hosszúsági (-180 és 180 között) és szélességi "
"(-90 és 90 között) értéket kell tartalmaznia"

#: geovisio/web/params.py:176
msgid "Parameter bbox must be in format [minX, minY, maxX, maxY]"
msgstr "A `bbox` paraméter elvárt formátuma [minX, minY, maxX, maxY]"

#: geovisio/web/params.py:213
#, python-format
msgid "Parameter %(p)s must be coordinates in lat,lon format"
msgstr "A `%(p)s` paraméternek lat,lon formátumú koordinátáknak kell lennie"

#: geovisio/web/params.py:216
#, python-format
msgid "Longitude in parameter %(p)s is not valid (should be between -180 and 180)"
msgstr ""
"A `%(p)s` paraméterben megadott hosszúsági fok nem érvényes (-180 és 180 "
"között kell lennie)"

#: geovisio/web/params.py:217
#, python-format
msgid "Latitude in parameter %(p)s is not valid (should be between -90 and 90)"
msgstr ""
"A `%(p)s` paraméterben megadott szélességi fok nem érvényes (-90 és 90 "
"között kell lennie)"

#: geovisio/web/params.py:240 geovisio/web/params.py:253
#, python-format
msgid ""
"Parameter %(p)s is invalid (should be a distance range in meters like "
"\"5-15\")"
msgstr ""
"`%(p)s` paraméter érvénytelen (méterben megadott távolságtartománynak "
"kellene lennie, például \"5-15\")"

#: geovisio/web/params.py:246
#, python-format
msgid "Parameter %(p)s has a min value greater than its max value"
msgstr ""
"`%(p)s` paraméterben a legkisebb (min) érték nagyobb, mint a legnagyobb (max)"

#: geovisio/web/params.py:320
#, python-format
msgid "Parameter %(p)s must be a valid list"
msgstr "`%(p)s` paraméternek érvényes listának kell lennie"

#: geovisio/web/params.py:444
msgid "Unsupported sortby parameter: invalid column name"
msgstr ""
"Nem támogatott sorba rendezés (`sortby`) paraméter: érvénytelen oszlopnév"

#: geovisio/web/params.py:452
msgid "Unsupported sortby parameter: syntax isn't correct"
msgstr ""
"Nem támogatott sorba rendezési (`sortby`) paraméter: a szintaxis nem helyes"

#: geovisio/web/params.py:478
#, python-format
msgid "limit parameter should be a valid, positive integer (between 1 and %(v)s)"
msgstr ""
"A `limit` paraméternek érvényes, pozitív egész számnak kell lennie (1 és %(v)"
"s között)"

#: geovisio/web/params.py:481
#, python-format
msgid "limit parameter should be an integer between 1 and %(v)s"
msgstr "A `limit` paraméternek 1 és %(v)s közötti egész számnak kell lennie"

#: geovisio/web/params.py:492
msgid "longitude needs to be between -180 and 180"
msgstr "A földrajzi hosszúságnak (longitude) -180 és 180 között kell lennie"

#: geovisio/web/params.py:502
msgid "latitude needs to be between -90 and 90"
msgstr "A földrajzi szélességnek (latitude) -90 és 90 között kell lennie"

#: geovisio/web/pictures.py:189
msgid "Tiles are not available for flat pictures"
msgstr "A lapos képekhez nem érhető el csempe"

#: geovisio/web/pictures.py:194
msgid "Column parameter is invalid, should be an integer"
msgstr ""
"Érvénytelen az oszlop (`column`) paramétere; egész számnak kellene lennie"

#: geovisio/web/pictures.py:197
msgid "Column parameter is invalid"
msgstr "Érvénytelen az oszlop (`column`) paramétere"

#: geovisio/web/pictures.py:202
msgid "Row parameter is invalid, should be an integer"
msgstr "Érvénytelen a sor (`row`) paramétere; egész számnak kellene lennie"

#: geovisio/web/pictures.py:205
msgid "Row parameter is invalid"
msgstr "Érvénytelen a sor (`row`) paramétere"

#: geovisio/web/reports.py:89 geovisio/web/reports.py:99
msgid "Impossible to create a Report"
msgstr "Nem lehet jelentést (report) létrehozni"

#: geovisio/web/reports.py:91
msgid "Parameter for creating a Report should be a valid JSON"
msgstr ""
"A jelentés (`report`) létrehozásához használt paraméternek érvényes JSON-nak "
"kell lennie"

#: geovisio/web/reports.py:144
msgid "Only authenticated users can access reports"
msgstr "Jelentéshez csak hitelesített felhasználó férhet hozzá"

#: geovisio/web/reports.py:148 geovisio/web/reports.py:266
msgid "Report doesn't exist"
msgstr "A jelentés nem létezik"

#: geovisio/web/reports.py:157
msgid "You're not authorized to access this report"
msgstr "Nincs jogosultságod a jelentéshez való hozzáférésre"

#: geovisio/web/reports.py:277
msgid "You're not authorized to edit this Report"
msgstr "Nincs jogosultságod a jelentés szerkesztésére"

#: geovisio/web/reports.py:284
msgid "Impossible to edit the Report"
msgstr "Nem lehet szerkeszteni a jelentést"

#: geovisio/web/reports.py:286
msgid "Parameter for editing the Report should be a valid JSON"
msgstr ""
"A jelentés (`report`) szerkesztéséhez használt paraméternek érvényes JSON-"
"nak kell lennie"

#: geovisio/web/reports.py:349 geovisio/web/reports.py:392
#: geovisio/web/upload_set.py:265 geovisio/web/upload_set.py:385
msgid "Impossible to parse parameters"
msgstr "Nem lehet elemezni a paramétereket"

#: geovisio/web/reports.py:352
msgid "You're not authorized to list reports"
msgstr "Nincs jogosultságod a jelentések listázására"

#: geovisio/web/rss.py:22
#, python-format
msgid "Sequence \"%(name)s\" by \"%(user)s\" was captured on %(date)s."
msgstr "%(user)s felhasználó %(name)s sorozatát ekkor lett rögzítve: %(date)s."

#: geovisio/web/rss.py:49
msgid "GeoVisio collections"
msgstr "GeoVisio gyűjtemények"

#: geovisio/web/rss.py:51
msgid "List of collections from this GeoVisio server"
msgstr "Ezen GeoVisio-kiszolgáló (szerver) gyűjteményeinek listája"

#: geovisio/web/tokens.py:101 geovisio/web/tokens.py:144
#: geovisio/web/tokens.py:232
msgid "Impossible to find token"
msgstr "Nem lehet megtalálni a tokent"

#: geovisio/web/tokens.py:182
msgid "Impossible to generate a new token"
msgstr "Nem lehet új tokent generálni"

#: geovisio/web/tokens.py:237
msgid "Token already claimed by another account"
msgstr "A tokent már egy másik fiók megigényelte"

#: geovisio/web/upload_set.py:133
msgid "Impossible to create an UploadSet"
msgstr "Nem lehet feltöltéskészletet (UploadSet) létrehozni"

#: geovisio/web/upload_set.py:135
msgid "Parameter for creating an UploadSet should be a valid JSON"
msgstr ""
"A feltöltéskészlet (UploadSet) létrehozásához használt paraméternek érvényes "
"JSON-nak kell lennie"

#: geovisio/web/upload_set.py:181 geovisio/web/upload_set.py:214
#: geovisio/web/upload_set.py:726
msgid "UploadSet doesn't exist"
msgstr "Ez a feltöltéskészlet (UploadSet) nem létezik"

#: geovisio/web/upload_set.py:216
msgid "You're not authorized to list pictures in this upload set"
msgstr "Ebben a feltöltéskészletben nincs jogosultságod képeket listázni"

#: geovisio/web/upload_set.py:303
msgid ""
"Parameter `override_capture_time` is not a valid datetime, it should be "
"an iso formated datetime (like '2017-07-21T17:32:28Z')."
msgstr ""
"Az `override_capture_time` paraméter nem érvényes dátum. ISO formátumú "
"dátumnak kell lennie (például '2017-07-21T17:32:28Z')."

#: geovisio/web/upload_set.py:370
msgid "No file was sent"
msgstr "Nem lett elküldve fájl"

#: geovisio/web/upload_set.py:536 geovisio/web/upload_set.py:712
#, python-format
msgid "UploadSet %(u)s does not exist"
msgstr "%(u)s feltöltéskészlet (UploadSet) nem létezik"

#: geovisio/web/upload_set.py:540
msgid "You're not authorized to add picture to this upload set"
msgstr "Nincs jogosultságod képet hozzáadni ehhez a feltöltéskészlethez"

#: geovisio/web/upload_set.py:580
msgid "The item has already been added to this upload set"
msgstr "Az elem már hozzá lett adva ehhez a feltöltéskészlethez"

#: geovisio/web/upload_set.py:587
msgid "The same picture has already been sent in a past upload"
msgstr "Ugyanezt a képet már elküldték egy korábbi feltöltés során"

#: geovisio/web/upload_set.py:630
msgid "Impossible to open file as image. The only supported image format is jpg."
msgstr ""
"Nem lehet képként megnyitni a fájlt. Az egyetlen támogatott képformátum a "
"jpg."

#: geovisio/web/upload_set.py:716
msgid "You're not authorized to complete this upload set"
msgstr "Nincs jogosultságod a feltöltéskészlet befejezésére"

#: geovisio/web/upload_set.py:763
msgid "You're not authorized to delete this upload set"
msgstr "Nincs jogosultságod a feltöltéskészlet törlésére"

#: geovisio/web/users.py:82
msgid "Impossible to find user"
msgstr "Nem lehet megtalálni a felhasználót"

#: geovisio/web/users.py:158
msgid ""
"No search parameter given, you should provide `q=<pattern>` as query "
"parameter"
msgstr ""
"Nincs megadva keresési paraméter. Meg kell adnod egy `q=<pattern>` "
"lekérdezési paramétert"

#: geovisio/web/utils.py:55
msgid "No default account defined, please contact your instance administrator"
msgstr ""
"Nincs alapértelmezett fiók meghatározva. Lépj kapcsolatba a Panoramax-"
"példány rendszergazdájával"
